### ISSUE TITLE
Resizing PNG increases size instead reducing

### ISSUE THREAD

**Issue by victorkurauchi** [humaans/next-img#6]
Hi,
I started using this plugin (great work btw) this week and am trying to run a few resizing and optimisations with PNG and JPG files.
So far, no issues with JPG.

Today i'm running the resize for my PNG file and i noticed the final result in /resources contain a file that has a bigger size than the original.

Do you happen to know what would be the cause for this behaviour ? 

Thanks a lot!

my code:
```
import { Picture } from 'next-img';
<Picture src={require('../public/images/proposal.png?sizes=375,800')} />
```

Result in `/resources` folder:
<img width="925" alt="Screen Shot 2020-08-06 at 13 15 11" src="https://user-images.githubusercontent.com/2061031/89555938-0c2e4e80-d7e7-11ea-90d9-bca073efa402.png">

My original image in `src/public/images` folder:
<img width="900" alt="Screen Shot 2020-08-06 at 13 17 08" src="https://user-images.githubusercontent.com/2061031/89556008-26682c80-d7e7-11ea-9eff-1484ea4e91df.png">

original size dimension: 2880x1036

**Comment by KidkArolis** [comment]
Hm, that's strange. I'll have a closer look tmrw. Any chance you could share the image, or try reproducing the issue with some public image?

**Comment by victorkurauchi** [comment]
hey @KidkArolis thanks for replying. Yeah i'll double check if i can share the image. Otherwise will reproduce with a public one!
thanks

**Comment by victorkurauchi** [comment]
hi @KidkArolis here's the png I used in my tests
![hero](https://user-images.githubusercontent.com/2061031/89668256-da36ee00-d8b3-11ea-98c1-15cae64787b1.png)
![proposal](https://user-images.githubusercontent.com/2061031/89668262-de630b80-d8b3-11ea-8674-d4ae01138354.png)

**Comment by KidkArolis** [comment]
I had a quick look into this.

The issue here is that these images are not very suited for .png format (png is a lossless image format). If you re-save these images as .jpg you will immediately get a smaller file size right off the bat. And then, passing those through next-img, you'll get even more compression across both jpg and webp outputs, depending on your plugin configuration.

If you keep them as png, then they get recompressed as part of the resizing process, and the sharp optimisation is not as effective as it could be if the best optimisation plugins were used. I briefly talk about it in the FAQ in the readme: https://github.com/humaans/next-img#faq and why it's not part of the next-img.

In other words, under normal circumstances, where normal in this case would be to use jpg for photos, not png, the plugin should work as expected:

- yields much smaller file size **webp image** compared to original
- yields smaller file size **jpg image** compared to original (depending on jpg quality plugin configuration setting)

And your case I'd say is a bit of an edge case, since you're using png for a photo, which:

- yields slightly smaller file size **webp image** compared to original (lossless by default because source is png)
- yields larger file size **png image**, because the plugin is not maximally optimizing png images

In the future, we might introduce an ability to add further png optimization plugins into the pipeline. But in a general case that should not be necessary. My recommendation is to use jpg format for these specific source images (since they're photos), which should yield the smallest file sizes with imperceptible quality drop (you might have to bump up the `jpeg: { quality: 80 }` setting though).

**Comment by victorkurauchi** [comment]
thanks a lot for the reply @KidkArolis . That helped and I'll take this in consideration when using the plugin.
