### ISSUE TITLE
Error: Missing an optimised image. Make sure to rerun next-img.

### ISSUE THREAD

**Issue by thedevdavid** [humaans/next-img#9]
Hey!

I've run into an issue. I had an image (hero.jpg) which I've modified later. And from that point, I can't build or deploy my app to Vercel, because it responds every time with this error:

`Error: Missing an optimised image hero-2160-b8e9d34d1c7f658b0b2de7e82f64b291.jpg. Make sure to rerun next-img.`

It works perfectly on dev. But when deploying to Vercel or building locally:

![image](https://user-images.githubusercontent.com/15244882/93501809-3874d900-f916-11ea-8402-a57aee76c40a.png)

If I run `npx next-img` I get this result: 
![image](https://user-images.githubusercontent.com/15244882/93502127-a1f4e780-f916-11ea-816f-eaeaa1b6cd47.png)

What do you think? Am I missing something?

(When opting out from persistent caching, it works with `persistentCache: false,`)

**Comment by KidkArolis** [comment]
Sorry for the late reply. In case this is useful, this seems to me that the optimized images have not been checked in into the repo. When you run `next` locally, the plugin will output the images to `resources`, if that's not in the git repo, a CI / Vercel build will fail, because those images are not there and the plugin explicitly doesn't rebuild them, unless `persistentCache` is set to `false`.
